# documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.3
  - oldrel
  - release
  - devel

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: false

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

#r_build_args: "--no-build-vignettes"
#r_check_args: "--no-build-vignettes --as-cran"

r_binary_packages:
  - stringi
  - magrittr
  - curl
  - jsonlite
  - Rcpp
  - RcppEigen
  - openssl
  - utf8
  - gss
  - haven
  - minqa
  - mvtnorm
  - nloptr
  - SparseM
  - httpuv
  - markdown
  - sem
  - readxl
  - openxlsx
  - pander
  - lme4
  - psych
  - git2r
  - data.table
#  - rlang
#  - bindrcpp
#  - purrr
#  - tidyr
#  - dplyr
#  - readr

r_packages:
  - rlang
  - bindrcpp
  - purrr
  - tidyr
  - dplyr
  - readr
  - covr
  - ggthemes
  - jcolors
  - oompaBase
  - palr
  - coin
  - jmv
  - sjstats
  - WRS2
#  - pals
  - scico
  - viridisLite

# "These installs will be faster than source installs, but may not always be the most recent version"
# https://docs.travis-ci.com/user/languages/r/#Additional-Dependency-Fields

     - os: osx
       osx_image: xcode9.3beta
     - os: osx
       osx_image: xcode9.2
       before_install:
         - brew install curl
         - brew link --force curl
     - os: osx
       osx_image: xcode9.2
     - os: osx
       osx_image: xcode7.3
       #r_build_args: '--no-build-vignettes'
       #r_check_args: '--ignore-vignettes --no-examples'

 addons:
   apt:
     packages:
     - libcurl4-openssl-dev
     - libxml2-dev
     - libgsl0-dev

 repos:
   CRAN: https://cloud.r-project.org
   ropensci: http://packages.ropensci.org

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
