# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false
fortran: true
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

r_binary_packages:
 - ggthemes
 - jcolors
 - oompaBase
 - palr
 - pals
 - scico
 - viridisLite
 - paletteer
 - git2r
 - rlang
 - testthat
 - ggplot2
 - covr


addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev
    - libgit2-dev   # (package on e.g. Debian and Ubuntu)
    - libgit2-devel # (package on e.g. Fedora, CentOS and RHEL)
    - libgit2

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
