# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
fortran: false

# Note: http test servers are flaky and we want to minimze false positives
# so we skip examples and vignettes (but not unit tests) on OS X.

matrix:
  include:
#   precise is getting decommissioned on Travis, so better to leave it out
   - os: linux
      dist: trusty
      sudo: required
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
      sudo: false
      env: R_CODECOV = true
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode7.3
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr
  r_binary_packages:
  # dependencies for ggstatsplot
  - apaTables
  - car
  - coin
  - crayon
  - devtools
  - dplyr
  - effsize
  - ggExtra
  - ggplot2
  - ggrepel
  - grid
  - jmv
  - magrittr
  - MASS
  - plyr
  - rlang
  - RVAideMemoire
  - sfsmisc
  - sjstats
  - stats
  - userfriendlyscience
  - WRS2
  - datasets
  - grDevices
  - gtable
  - knitr
  - RColorBrewer
  - rmarkdown
  - testthat
  # dependencies of dependencies
  - backports
  - checkmate
  - abind
  - Formula
  - latticeExtra
  - acepack
  - htmlTable
  - httpuv
  - sourcetools
  - brew
  - arm
  - rematch
  - bindr
  - utf8
  - qvcalc
  - relimp
  - prettyunits
  - Hmisc
  - irlba
  - shiny
  - crosstalk
  - RSpectra
  - forcats
  - hms
  - Rook
  - StanHeaders
  - rpf
  - matrixcalc
  - mi
  - cellranger
  - lazyeval
  - mime
  - curl
  - openssl
  - stringr
  - reshape2
  - assertthat
  - bindrcpp
  - glue
  - pkgconfig
  - Rcpp
  - BH
  - plogr
  - pillar
  - SparseM
  - MatrixModels
  - THdata
  - rjson
  - base64enc
  - estimability
  - coda
  - colorspace
  - gnm
  - ca
  - progress
  - pbapply
  - gtools
  - RcppEigen
  - mnormt
  - lmerTest
  - pbivnorm
  - quadprog
  - numDeriv
  - ellipse
  - flashClust
  - leaps
  - scatterplot3d
  - minqa
  - nloptr
  - igraph
  - rgl
  - corpcor
  - matrixStats
  - rARPACK
  - permute
  - zoo
  - TMB
  - haven
  - snakecase
  - stringdist
  - stringi
  - downloader
  - htmltools
  - htmlwidgets
  - influenceR
  - readr
  - rstudioapi
  - rgexf
  - visNetwork
  - timeDate
  - timeSeries
  - gss
  - stabledist
  - evaluate
  - highr
  - markdown
  - yaml
  - gsl
  - OpenMx
  - sem
  - semTools
  - datatable
  - readxl
  - openxlsx
  - dichromat
  - munsell
  - labeling v
  - iridisLite
  - jsonlite
  - rex
  - httr
  - crayon
  - withr
  - broom
  - dplyr
  - tibble
  - pbkrtest
  - quantreg
  - modeltools
  - mvtnorm
  - multcomp
  - jmvcore
  - R6
  - ggplot2
  - PMCMR
  - emmeans
  - vcd
  - vcdExtra
  - GGally
  - BayesFactor
  - psych
  - GPArotation
  - afex
  - mvnormtest
  - lavaan
  - ggridges
  - ade4
  - cramer
  - dunntest
  - FactoMineR
  - lme4
  - mixOmics
  - multcompView
  - pls
  - pspearman
  - vegan
  - bayesplot
  - cli
  - lmtest
  - glmmTMB
  - magrittr
  - modelr
  - prediction
  - purrr
  - pwr
  - rlang
  - sandwich
  - sjlabelled
  - sjmisc
  - tidyr
  - tidyselect
  - BiasedUrn
  - datatree
  - DiagrammeR
  - diptest
  - digest
  - fBasics
  - MBESS
  - minpacklm
  - pander
  - plyr
  - rio
  - scales
  - SCRT
  - SuppDists
  - viridis
  - XML
  - xtable
  - reshape
  - mc2d

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov()'
