# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
#fortran: true
warnings_are_errors: true
use_bioc: true

r:
  - oldrel
  - release
  - devel

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - bindrcpp
        - RcppEigen
        - openssl
        - rlang
        - utf8
        - gss
        - haven
        - data.table
        - dplyr
        - purrr
        - tidyr
        - readr
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - lme4
        - httpuv
        - markdown
        - sem
        - readxl
        - openxlsx
        - pander

    - r: release
      os: osx
      osx_image: xcode9.3beta

    - r: release
      os: osx
      osx_image: xcode9.2
      before_install:
        - brew install curl
        - brew link --force curl

    - r: release
      os: osx
      osx_image: xcode7.3 # CRAN: El Capitan
      pandoc: false
      before_install:
        - curl -fLo /tmp/pandoc-1.12-1.dmg https://github.com/jgm/pandoc/releases/download/1.12/pandoc-1.12-1.dmg
        - sudo hdiutil attach /tmp/pandoc-1.12-1.dmg -mountpoint /Volumes/pandoc
        - sudo installer -pkg "/Volumes/pandoc/pandoc-1.12.pkg" -allowUntrusted -target /
        - sudo hdiutil detach /Volumes/pandoc
      env: PANDOC='mac-cran'


addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
